name: build_docker_images
on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      llvm_mos_repo:
        description: 'llvm-mos repo'
        required: true
        default: 'mrk-its/llvm-mos'
      llvm_mos_sdk_repo:
        description: 'llvm-mos-sdk repo'
        required: true
        default: 'llvm-mos/llvm-mos-sdk'
      llvm_mos_ref:
        description: 'llvm-mos ref'
        required: true
        default: 'lldb-mos'
      llvm_mos_sdk_ref:
        description: 'llvm-mos-sdk ref'
        required: true
        default: 'main'

env:
  LLVM_MOS_REPO: mrk-its/llvm-mos
  LLVM_MOS_REF: lldb-mos
  LLVM_MOS_SDK_REPO: llvm-mos/llvm-mos-sdk
  LLVM_MOS_SDK_REF: main

jobs:
  create_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout llvm-mos
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.llvm_mos_repo || env.LLVM_MOS_REPO }}
          path: docker/llvm-mos/llvm-mos
          ref: ${{ github.event.inputs.llvm_mos_ref || env.LLVM_MOS_REF }}

      - name: Checkout llvm-mos-sdk
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.llvm_mos_sdk_repo || env.LLVM_MOS_SDK_REPO }}
          path: docker/llvm-mos/llvm-mos-sdk
          ref: ${{ github.event.inputs.llvm_mos_sdk_ref || env.LLVM_MOS_SDK_REF }}

      - name: Set short sha
        id: short_sha
        run: echo -e "::set-output name=llvm_mos::$(cd docker/llvm-mos/llvm-mos; git rev-parse --short HEAD)\n::set-output name=llvm_mos_sdk::$(cd docker/llvm-mos/llvm-mos-sdk; git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.short_sha.outputs.llvm_mos }} ${{ steps.short_sha.outputs.llvm_mos_sdk }}          

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push llvm-mos
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mrkits/llvm-mos:latest,mrkits/llvm-mos:${{ steps.short_sha.outputs.llvm_mos }}-${{ steps.short_sha.outputs.llvm_mos_sdk }}
          context: docker/llvm-mos
          cache-from: type=registry,ref=mrkits/llvm-mos:llvm-mos-buildcache
          cache-to: type=registry,ref=mrkits/llvm-mos:llvm-mos-buildcache,mode=max

      - name: Set rust-mos short sha
        id: rust_mos
        run: echo -e "::set-output name=short_sha::$(cd docker/rust-mos/rust-mos; git rev-parse --short HEAD)"

      - name: Build and push rust-mos
        id: docker_build_3
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mrkits/rust-mos:latest,mrkits/rust-mos:${{ steps.short_sha.outputs.llvm_mos }}-${{ steps.short_sha.outputs.llvm_mos_sdk }}-${{ steps.rust_mos.outputs.short_sha }}
          file: docker/rust-mos/Dockerfile
          context: .
          build-args: |
            LLVM_MOS_SDK_IMAGE=mrkits/llvm-mos:latest