name: llvm_cross_build
on:
  workflow_dispatch:
    inputs:
      llvm_mos_repo:
        description: 'llvm-mos repo'
        default: 'llvm-mos/llvm-mos'
        type: string
      llvm_mos_sdk_repo:
        description: 'llvm-mos-sdk repo'
        default: 'llvm-mos/llvm-mos-sdk'
        type: string
      llvm_mos_ref:
        description: 'llvm-mos ref'
        default: 'main'
        type: string
      llvm_mos_sdk_ref:
        description: 'llvm-mos-sdk ref'
        default: 'main'
        type: string


jobs:
  amd64_image:
    uses: ./.github/workflows/cross-build-llvm-mos.yml
    with:
      arch: amd64
    secrets: inherit

  arm64_image:
    uses: ./.github/workflows/cross-build-llvm-mos.yml
    with:
      arch: arm64
    secrets: inherit

  final:
    runs-on: ubuntu-latest
    needs:
      - amd64_image
      - arm64_image
    steps:
      - name: hello
        run: echo preparing multi-arch image
